brew install --cask adobe-creative-cloud
brew install --cask adoptopenjdk
brew install --cask bartender
brew install --cask blackhole-16ch
brew install --cask brave-browser
brew install --cask chromedriver
brew install --cask discord
brew install --cask docker
brew install --cask flutter
brew install --cask font-jetbrains-mono
brew install --cask google-chrome
brew install --cask gpg-suite
brew install --cask jetbrains-toolbox
brew install --cask karabiner-elements
brew install --cask kindle
brew install --cask macmediakeyforwarder
brew install --cask microsoft-teams
brew install --cask neovim-nightly
brew install --cask notion
brew install --cask sage
brew install --cask signal
brew install --cask slack
brew install --cask spotify
brew install --cask stremio
brew install --cask syncplay
brew install --cask transmission
brew install --cask virtualbox
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask zoomus
