brew cask install adobe-creative-cloud
brew cask install adoptopenjdk
brew cask install bartender
brew cask install brave-browser
brew cask install chromedriver
brew cask install discord
brew cask install docker
brew cask install flutter
brew cask install font-jetbrains-mono
brew cask install gpg-suite
brew cask install jetbrains-toolbox
brew cask install karabiner-elements
brew cask install kindle
brew cask install macmediakeyforwarder
brew cask install microsoft-teams
brew cask install notion
brew cask install sage
brew cask install signal
brew cask install slack
brew cask install spotify
brew cask install stremio
brew cask install syncplay
brew cask install transmission
brew cask install virtualbox
brew cask install visual-studio-code
brew cask install vlc
brew cask install zoomus
