brew install automake
brew install cabal-install
brew install cmake
brew install cvc4
brew install eprover
brew install gh
brew install git
brew install haskell-stack
brew install hugo
brew install jq
brew install mas
brew install neovim
brew install node
brew install opam
brew install openjdk
brew install pypy3
brew install python
brew install tree
brew install unrar
brew install wget
brew install zsh-autosuggestions
brew install zsh-git-prompt
brew install zsh-history-substring-search
