brew install adwaita-icon-theme
brew install automake
brew install cask
brew install cmake
brew install coreutils
brew install cvc4
brew install dafny
brew install eprover
brew install expat
brew install gh
brew install git
brew install gpatch
brew install gperf
brew install gtksourceview
brew install gtksourceview3
brew install hugo
brew install jq
brew install libtermkey
brew install libvterm
brew install libxml2
brew install luajit
brew install luajit-openresty
brew install mas
brew install msgpack
brew install node
brew install pypy3
brew install python
brew install yices
brew install tree
brew install unrar
brew install wget
brew install zsh-autosuggestions
brew install zsh-git-prompt
brew install zsh-history-substring-search
