brew tap cvc4/cvc4
brew tap flschweiger/flutter
brew tap fraguinha/fraguinha
brew tap github/gh
brew tap homebrew/cask
brew tap homebrew/cask-fonts
brew tap homebrew/cask-versions
brew tap homebrew/core
brew tap sri-csl/sri-csl
